name: ratgtex
channels:
  - bioconda
  - conda-forge
dependencies:
  - bcftools
  - bioconductor-impute  # for covariates
  - bioconductor-qvalue  # for tensorqtl
  - bioconductor-snpstats  # for covariates
  - bx-python
  - dask<2024.2  # for tensorqtl (pandas-plink)
  - gatk4
  - gtfparse
  - pandas
  - pandas-plink  # for tensorqtl
  - plink2=2
  - pysam
  - r-argparser
  - r-foreach  # for leafcutter
  - r-tidyverse
  - regtools
  - rpy2  # for tensorqtl
  - rsem
  - scikit-learn
  - scipy
  - snakemake
  - snakemake-executor-plugin-slurm
  - star
  - tabix
  - pip:
    - tensorqtl
    - torch==2.3.1 # for tensorqtl
