name: ratgtex
channels:
  - bioconda
  - conda-forge
dependencies:
  - bcftools
  - bioconductor-impute
  - bioconductor-qvalue
  - bx-python
  - fastparquet
  - gatk4
  - gtfparse
  - pandas
  - plink2=2
  - pysam
  - r-argparser
  - regtools
  - rpy2
  - rsem
  - scikit-learn
  - scipy
  - snakemake
  - snakemake-executor-plugin-slurm
  - star
  - tabix
  - pip:
    - tensorqtl
